import { ReactNode } from 'react'
import type { Metadata } from 'next'
// import {JetBrains_Mono} from 'next/font/google';
import './globals.css'

import Header from '@/layout/Header'
import Content from '@/layout/Content'
import Footer from '@/layout/Footer'
import { cn } from '@/lib/utils'
import { ViewportLayout } from 'next/dist/lib/metadata/types/extra-types'

// const jetBrainsMono = JetBrains_Mono(
//     {
//         subsets: ['latin'],
//         variable: '--font-dm-mono',
//         weight: ['400', '500', '600', '700'],
//     }
// );

export const metadata: Metadata = {
    title: 'Find Guide | Home',
    description: 'Generated by choice next app',
}

export const viewport: ViewportLayout = {
    width: 'device-width, shrink-to-fit=no',
    maximumScale: 1,
    userScalable: false,
}

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode
}>) {
    return (
        <html lang="en">
            <body className={cn('flex min-h-dvh flex-col')}>
                <Header />
                <Content>{children}</Content>
                {/*<Footer/>*/}
            </body>
        </html>
    )
}
